[filter]
timeout = 5                     # proxies timeout in seconds.

[options]
scrape = true                    # scrape proxies from url.csv.
threads = 800                    # maximum checking threads.
scrape_threads = 50              # maximum threads while scraping proxies.
save_transparent = false         # transparent proxies don't hide your real IP.
show_dead_proxies = false        # print dead proxies in console, disable it can give better performances

[dev]
debug = false                     # show errors