[filter]
timeout = 10                     # proxies timeout in seconds.

[options]
scrape = false                    # scrape proxies from url.csv.
threads = 500                    # maximum checking threads.
scrape_threads = 50              # maximum threads while scraping proxies.
save_transparent = false         # transparent proxies don't hide your real IP.